update Jenkinsfile for system tests
Signed-off-by: Vladimir Shishkin <vladimir.shishkin@dsr-corporation.com>

diff --git a/Jenkinsfile.cd b/Jenkinsfile.cd
--- a/Jenkinsfile.cd
+++ b/Jenkinsfile.cd
@@ -68,7 +68,7 @@ def systemTests = { component ->
 
     String prefix = "System Tests ($component)"
     String defaultNetwork = 'pool-network'
-    int nodesNum = 4
+    int nodesNum = 7
 
     String indySDKVersion
     String indyCryptoVersion
@@ -93,6 +93,54 @@ def systemTests = { component ->
         sh "docker container prune -f"
         sh "docker network prune -f"
     }
+	
+	def dockerSetup = { component ->
+		dir("environment/docker/pool"){
+            stage("Patch core dockerfile") {
+                // TODO update dockerfile instead of patching
+                sh """
+                    sed -i 's/repo.sovrin.org\\/deb xenial .*\\+"/repo.sovrin.org\\/deb xenial $component"/g' core.ubuntu.dockerfile
+                    sed -i 's/sdk\\/deb xenial .\\+"/sdk\\/deb xenial stable"/g' core.ubuntu.dockerfile
+                    sed -i 's/\\(apt-get install -y indy-node libindy\\)/&=$indySDKVersion python3-indy-crypto=$indyCryptoVersion libindy-crypto=$indyCryptoVersion/g' core.ubuntu.dockerfile
+                    sed -i 's/\\(RUN pip3 install python3-indy\\)/&==$indySDKVersion pytest/g' core.ubuntu.dockerfile
+                """
+            }
+
+            stage("Run pool") {
+                 echo "$prefix: Running nodes..."
+                sh "./pool_start.sh $nodesNum"
+                pool_nodes = sh(script: 'docker ps', returnStdout: true)
+                echo "$prefix: $pool_nodes"
+            }
+
+            stage("Ensure node services started") {
+                // TODO explore and fix the reason why they (mostly Node1) not always active
+                for (nodeNum = 1; nodeNum <= nodesNum; nodeNum++) {
+                    for (service in ['indy-node', 'indy-node-control']) {
+                        sh """
+                            for i in 1 2 3; do
+                                echo "Ensure $service on node${nodeNum} is started (try #\$i)"
+                                docker exec -t -u 0 node${nodeNum} systemctl start $service
+                                if [ "\$(docker exec -u 0 node${nodeNum} systemctl is-active $service)" = "active" ]; then
+                                    exit 0
+                                fi
+                            done
+
+                            echo 'Failed to start $service on node${nodeNum}'
+                            exit 1
+                        """
+                    }
+                }
+            }
+
+            stage("Prepare and run client") {
+                sh '''
+                    sed -i 's/\\(docker exec -it\\)/#&/g' client_start.sh
+                    ./client_for_pool_start.sh
+                '''
+            }
+        }
+	}
 
     node("ubuntu") {
         stage("Cleanup docker") {
@@ -124,52 +172,9 @@ def systemTests = { component ->
         }
 
         try {
-            dir("environment/docker/pool"){
-                stage("Patch core dockerfile") {
-                    // TODO update dockerfile instead of patching
-                    sh """
-                        sed -i 's/repo.sovrin.org\\/deb xenial .*\\+"/repo.sovrin.org\\/deb xenial $component"/g' core.ubuntu.dockerfile
-                        sed -i 's/sdk\\/deb xenial .\\+"/sdk\\/deb xenial stable"/g' core.ubuntu.dockerfile
-                        sed -i 's/\\(apt-get install -y indy-node libindy\\)/&=$indySDKVersion python3-indy-crypto=$indyCryptoVersion libindy-crypto=$indyCryptoVersion/g' core.ubuntu.dockerfile
-                        sed -i 's/\\(RUN pip3 install python3-indy\\)/&==$indySDKVersion pytest/g' core.ubuntu.dockerfile
-                    """
-                }
-
-                stage("Run pool") {
-                    echo "$prefix: Running nodes..."
-                    sh "./pool_start.sh $nodesNum"
-                    pool_nodes = sh(script: 'docker ps', returnStdout: true)
-                    echo "$prefix: $pool_nodes"
-                }
-
-                stage("Ensure node services started") {
-                    // TODO explore and fix the reason why they (mostly Node1) not always active
-                    for (nodeNum = 1; nodeNum <= nodesNum; nodeNum++) {
-                        for (service in ['indy-node', 'indy-node-control']) {
-                            sh """
-                                for i in 1 2 3; do
-                                    echo "Ensure $service on node${nodeNum} is started (try #\$i)"
-                                    docker exec -t -u 0 node${nodeNum} systemctl start $service
-                                    if [ "\$(docker exec -u 0 node${nodeNum} systemctl is-active $service)" = "active" ]; then
-                                        exit 0
-                                    fi
-                                done
-
-                                echo 'Failed to start $service on node${nodeNum}'
-                                exit 1
-                            """
-                        }
-                    }
-                }
-
-
-                stage("Prepare and run client") {
-                    sh '''
-                        sed -i 's/\\(docker exec -it\\)/#&/g' client_start.sh
-                        ./client_for_pool_start.sh
-                    '''
-                }
-            }
+			stage("Setup docker") {
+				dockerSetup()
+			}
 
             stage("Prepare tests") {
                 // https://github.com/moby/moby/issues/34096
